host: "0.0.0.0"
port: 8000
center: "localhost:9000"

mongo_connection: "mongodb://root:123456@localhost:27017/"
redis_host: "localhost"
redis_port: "6379"
redis_background_db: 2
redis_db: 1
redis_password: ""

baidu_login_cookie: ""
